### ISSUE TITLE
Curious why resolve points to src directory?

### ISSUE THREAD

**Issue by nullbio** [simonh1000/elm-webpack-starter#18]
Hi Simon, just a basic question for you, wondering what the rationale was behind having your "resolve" object point to the src/ directory instead of just having it default to the project root. Is there a specific reason for this, or was it just aesthetics (you liked having source code in src/). Thanks.

**Comment by nullbio** [comment]
On another note, why the change back to webpack-dev-server as well?

**Comment by simonh1000** [comment]
Hi. On the resolve, it just seems cleaner - and i often have a directory called `ignore` that I don't want getting caught up.
the  webpack-dev-server has been a bit frustrating - it seemed for a while that webpack-serve was the recommended way, but now the advice has changed back to  webpack-dev-server  so I reverted. From an elm perspective it does help because dev-server seems better at surpressing webpack messages so that we can focus on the elm errors from the compiler

**Comment by nullbio** [comment]
Thanks @simonh1000 that explains things. :+1:
