### ISSUE TITLE
Add a test setup and example test

### ISSUE THREAD

**Issue by alexkrauss** [simonh1000/elm-webpack-starter#2]
Great starter template... but... **If you can't test it, don't build it**

...so a decent template should include a setup for tests.

**Comment by simonh1000** [comment]
When I first wrote this, elm-test only seemed to be able to copy over dependencies when it was first installed. So I didn't think I was helping anyone much if I set up testing prematurely. That is no longer the case so your issue is definitely merited.

Elm-test does a complete separate compilation (as do some of the IDE tools). Do you think it makes sense to run tests in parallel with the dev environment. I see my computer slow down too often that I only run tests seperately. (Also I tend to find myself doing UI work where testing is - arguably - less vital at different times from doing tricky data transformations, where testing is very useful).

**Comment by simonh1000** [comment]
If you had time to try out the tests branch https://github.com/simonh1000/elm-webpack-starter/tree/tests I'd be very greatful

**Comment by alexkrauss** [comment]
:thumbsup:

Two minor things:
* I find relying on global install of elm-test a little strange and unnecessary. It also makes `yarn` fail when elm-test is not yet installed globally at that point. Instead, I simply added elm-test as a devDependency. Then it works out of the box, and tests can be run using `yarn test`
* The link in the readme section is broken.

I like running tests continously with a watcher, and this just works with `yarn test --watch`, so developers can decide whether to run it alongside the dev loop or not.

**Comment by simonh1000** [comment]
I'm going to leave elm-test out for the moment. Your arguments make sense, but the elm-test people encourage a global install, so I'm going to go that way for the moment. Thanks for encouraging me to add this key feature
